FROM ghcr.io/cirruslabs/flutter:3.10.5 as build

WORKDIR /usr/src/app

RUN flutter doctor

RUN flutter config --enable-web

COPY pubspec.yaml pubspec.yaml

COPY pubspec.lock pubspec.lock

RUN flutter pub get

COPY . .

RUN flutter build web --release

EXPOSE 8080

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build/web /usr/share/nginx/html
