# fly.toml file generated for parlamento-dev on 2022-11-12T00:17:36Z

app = "parlamento-dev"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
# fly.toml file generated for maersk-inbound on 2022-10-26T11:32:19+01:00

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
 