FROM mcr.microsoft.com/dotnet/sdk:6.0.402-alpine3.16-amd64

WORKDIR /usr/src/app

RUN dotnet --info

COPY backend.sln .

# Copy csproj and restore as distinct layers
COPY test/test.csproj ./test/test.csproj
COPY integration-tests/integration-tests.csproj ./integration-tests/integration-tests.csproj
COPY src/backend.csproj ./src/backend.csproj

RUN dotnet restore

COPY src src
COPY test test
COPY integration-tests integration-tests

CMD [ "dotnet", "test", "--no-restore", "--verbosity", "normal" ]