FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /usr/src/app

RUN dotnet --info

RUN dotnet tool install --global dotnet-ef --version 8.0.0

# Copy csproj and restore as distinct layers
COPY global.json .
COPY Domain/Parlamento.Domain.csproj Domain/Parlamento.Domain.csproj
COPY Application/Parlamento.Application.csproj Application/Parlamento.Application.csproj
COPY Infrastructure/Parlamento.Infrastructure.csproj Infrastructure/Parlamento.Infrastructure.csproj
COPY src/backend.csproj src/backend.csproj

RUN dotnet restore src

RUN dotnet dev-certs https --trust

COPY Domain Domain
COPY Application Application
COPY Infrastructure Infrastructure
COPY src src

WORKDIR /usr/src/app/src

CMD [ "dotnet", "ef", "database", "update", "--project", ".", "--startup-project", ".", "--runtime", "linux-x64"]
