FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as build

ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /usr/src/app

RUN dotnet --info

RUN dotnet tool install --global dotnet-ef --version 8.0.0

# Copy csproj and restore as distinct layers
COPY global.json .
COPY src/backend.csproj src/backend.csproj

RUN dotnet restore src

RUN dotnet dev-certs https --trust

COPY src src

RUN dotnet ef database update --project src 

RUN dotnet publish --configuration Release -o build src

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/build .
COPY --from=build /usr/src/app/src/db.sqlite .

EXPOSE 8080

CMD ["dotnet", "backend.dll", "--urls", "http://0.0.0.0:8080"]
