using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260701000600_AddParliamentSummaries")]
public class AddParliamentSummaries : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "ParliamentSummaries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentDocumentContentId" integer NOT NULL,
                "ShortTitle" text NULL,
                "SummaryText" text NULL,
                "BulletPointsJson" text NULL,
                "GenerationStatus" text NOT NULL,
                "ModelName" text NOT NULL,
                "PromptVersion" text NOT NULL,
                "SourceDocumentHash" text NOT NULL,
                "ErrorMessage" text NULL,
                "ErrorDetails" text NULL,
                "GeneratedAtUtc" timestamp with time zone NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ParliamentSummaries" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentSummaries_ParliamentDocumentContents_ParliamentDocumentContentId"
                    FOREIGN KEY ("ParliamentDocumentContentId")
                    REFERENCES "ParliamentDocumentContents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentSummaries_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_ParliamentSummaries_ParliamentDocumentContentId"
                ON "ParliamentSummaries" ("ParliamentDocumentContentId");

            CREATE INDEX IF NOT EXISTS "IX_ParliamentSummaries_ProjectLawId_SourceDocumentHash_ModelName_PromptVersion"
                ON "ParliamentSummaries" ("ProjectLawId", "SourceDocumentHash", "ModelName", "PromptVersion");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ParliamentSummaries";
            """);
    }
}
