using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260703000100_AddProposalInteractions")]
public class AddProposalInteractions : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "ProjectLawInteractionStats" (
                "ProjectLawId" integer NOT NULL,
                "Impressions" integer NOT NULL DEFAULT 0,
                "SupportVotes" integer NOT NULL DEFAULT 0,
                "OpposeVotes" integer NOT NULL DEFAULT 0,
                "Skips" integer NOT NULL DEFAULT 0,
                "DetailOpens" integer NOT NULL DEFAULT 0,
                "SourceLinkClicks" integer NOT NULL DEFAULT 0,
                "DebateLinkClicks" integer NOT NULL DEFAULT 0,
                "PostVoteReveals" integer NOT NULL DEFAULT 0,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ProjectLawInteractionStats" PRIMARY KEY ("ProjectLawId"),
                CONSTRAINT "FK_ProjectLawInteractionStats_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "ProposalInteractionEvents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" integer NOT NULL,
                "ProjectLawId" integer NOT NULL,
                "InteractionType" integer NOT NULL,
                "IdempotencyKey" text NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ProposalInteractionEvents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProposalInteractionEvents_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ProposalInteractionEvents_Users_UserId"
                    FOREIGN KEY ("UserId")
                    REFERENCES "Users" ("Id")
                    ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_ProposalInteractionEvents_ProjectLawId"
                ON "ProposalInteractionEvents" ("ProjectLawId");

            CREATE INDEX IF NOT EXISTS "IX_ProposalInteractionEvents_UserId_ProjectLawId_InteractionType_CreatedAtUtc"
                ON "ProposalInteractionEvents" ("UserId", "ProjectLawId", "InteractionType", "CreatedAtUtc");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProposalInteractionEvents_UserId_ProjectLawId_IdempotencyKey"
                ON "ProposalInteractionEvents" ("UserId", "ProjectLawId", "IdempotencyKey")
                WHERE "IdempotencyKey" IS NOT NULL;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ProposalInteractionEvents";
            DROP TABLE IF EXISTS "ProjectLawInteractionStats";
            """);
    }
}
