using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260701000100_AddParliamentOpenDataImporter")]
public class AddParliamentOpenDataImporter : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE "ParliamentImportRuns" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "SourceKind" text NOT NULL,
                "Legislature" text NULL,
                "SourceReference" text NULL,
                "StartedAtUtc" timestamp with time zone NOT NULL,
                "FinishedAtUtc" timestamp with time zone NULL,
                "Status" text NOT NULL,
                "RecordsRead" integer NOT NULL,
                "RecordsInserted" integer NOT NULL,
                "RecordsUpdated" integer NOT NULL,
                "RecordsSkipped" integer NOT NULL,
                "RecordsFailed" integer NOT NULL,
                "ErrorMessage" text NULL,
                CONSTRAINT "PK_ParliamentImportRuns" PRIMARY KEY ("Id")
            );

            ALTER TABLE "ProjectLaws" ADD "SourceIdText" text NULL;
            ALTER TABLE "ProjectLaws" ADD "SourceHash" text NULL;
            ALTER TABLE "ProjectLaws" ADD "ImportedAtUtc" timestamp with time zone NULL;
            ALTER TABLE "ProjectLaws" ADD "LastImportRunId" integer NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeNumber" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeTypeCode" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeTypeDescription" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeSelection" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeObservations" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeTextSubstitution" text NULL;
            ALTER TABLE "ProjectLaws" ADD "InitiativeTextSubstitutionField" text NULL;

            CREATE TABLE "ParliamentImportErrors" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ParliamentImportRunId" integer NOT NULL,
                "SourceId" text NULL,
                "ErrorType" text NOT NULL,
                "Message" text NOT NULL,
                CONSTRAINT "PK_ParliamentImportErrors" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentImportErrors_ParliamentImportRuns_ParliamentImportRunId"
                    FOREIGN KEY ("ParliamentImportRunId")
                    REFERENCES "ParliamentImportRuns" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentImportSkips" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ParliamentImportRunId" integer NOT NULL,
                "SourceId" text NULL,
                "InitiativeTypeCode" text NULL,
                "InitiativeTypeDescription" text NULL,
                "Reason" text NOT NULL,
                "Message" text NULL,
                CONSTRAINT "PK_ParliamentImportSkips" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentImportSkips_ParliamentImportRuns_ParliamentImportRunId"
                    FOREIGN KEY ("ParliamentImportRunId")
                    REFERENCES "ParliamentImportRuns" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeAuthors" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "AuthorKind" text NOT NULL,
                "Name" text NULL,
                "Acronym" text NULL,
                "DeputySourceId" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeAuthors" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeAuthors_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeEvents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "SourceEventId" text NULL,
                "SourceActivityId" text NULL,
                "SourceObjectEventId" text NULL,
                "SourceTextId" text NULL,
                "PhaseCode" text NULL,
                "PhaseName" text NULL,
                "PhaseDate" text NULL,
                "Observation" text NULL,
                "ApprovedTextId" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeEvents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeEvents_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeDocuments" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentInitiativeEventId" integer NULL,
                "Scope" text NOT NULL,
                "Name" text NULL,
                "DocumentType" text NULL,
                "DocumentDate" text NULL,
                "Url" text NULL,
                "CommitteeId" text NULL,
                "CommitteeName" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeDocuments" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeDocuments_ParliamentInitiativeEvents_ParliamentInitiativeEventId"
                    FOREIGN KEY ("ParliamentInitiativeEventId")
                    REFERENCES "ParliamentInitiativeEvents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentInitiativeDocuments_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeInterventions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentInitiativeEventId" integer NULL,
                "PlenaryMeetingDate" text NULL,
                "SpeakerName" text NULL,
                "SpeakerParty" text NULL,
                "GovernmentMemberName" text NULL,
                "GovernmentMemberRole" text NULL,
                "StartTime" text NULL,
                "EndTime" text NULL,
                "VideoUrl" text NULL,
                "PublicationDiaryUrl" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeInterventions" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeInterventions_ParliamentInitiativeEvents_ParliamentInitiativeEventId"
                    FOREIGN KEY ("ParliamentInitiativeEventId")
                    REFERENCES "ParliamentInitiativeEvents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentInitiativeInterventions_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativePublications" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentInitiativeEventId" integer NULL,
                "Scope" text NOT NULL,
                "PublicationDate" text NULL,
                "Legislature" text NULL,
                "Number" text NULL,
                "Series" text NULL,
                "Type" text NULL,
                "TypeCode" text NULL,
                "DiaryUrl" text NULL,
                CONSTRAINT "PK_ParliamentInitiativePublications" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativePublications_ParliamentInitiativeEvents_ParliamentInitiativeEventId"
                    FOREIGN KEY ("ParliamentInitiativeEventId")
                    REFERENCES "ParliamentInitiativeEvents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentInitiativePublications_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeVotes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentInitiativeEventId" integer NULL,
                "SourceVoteId" text NULL,
                "Stage" text NOT NULL,
                "VoteDate" text NULL,
                "Description" text NULL,
                "Result" text NULL,
                "Unanimous" text NULL,
                "Detail" text NULL,
                "Meeting" text NULL,
                "MeetingType" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeVotes" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeVotes_ParliamentInitiativeEvents_ParliamentInitiativeEventId"
                    FOREIGN KEY ("ParliamentInitiativeEventId")
                    REFERENCES "ParliamentInitiativeEvents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentInitiativeVotes_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE TABLE "ParliamentInitiativeVoteBlocks" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ParliamentInitiativeVoteId" integer NOT NULL,
                "PartyAcronym" text NULL,
                "NumberOfDeputies" integer NULL,
                "IsUnanimousWithinParty" boolean NULL,
                "VotingOrientation" integer NOT NULL,
                "RawToken" text NULL,
                "ParseWarning" text NULL,
                CONSTRAINT "PK_ParliamentInitiativeVoteBlocks" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentInitiativeVoteBlocks_ParliamentInitiativeVotes_ParliamentInitiativeVoteId"
                    FOREIGN KEY ("ParliamentInitiativeVoteId")
                    REFERENCES "ParliamentInitiativeVotes" ("Id")
                    ON DELETE CASCADE
            );

            ALTER TABLE "ProjectLaws"
                ADD CONSTRAINT "FK_ProjectLaws_ParliamentImportRuns_LastImportRunId"
                FOREIGN KEY ("LastImportRunId")
                REFERENCES "ParliamentImportRuns" ("Id")
                ON DELETE SET NULL;

            CREATE INDEX "IX_ParliamentImportErrors_ParliamentImportRunId"
                ON "ParliamentImportErrors" ("ParliamentImportRunId");
            CREATE INDEX "IX_ParliamentImportRuns_SourceKind_Legislature_StartedAtUtc"
                ON "ParliamentImportRuns" ("SourceKind", "Legislature", "StartedAtUtc");
            CREATE INDEX "IX_ParliamentImportSkips_ParliamentImportRunId"
                ON "ParliamentImportSkips" ("ParliamentImportRunId");
            CREATE INDEX "IX_ParliamentInitiativeAuthors_ProjectLawId"
                ON "ParliamentInitiativeAuthors" ("ProjectLawId");
            CREATE INDEX "IX_ParliamentInitiativeDocuments_ParliamentInitiativeEventId"
                ON "ParliamentInitiativeDocuments" ("ParliamentInitiativeEventId");
            CREATE INDEX "IX_ParliamentInitiativeDocuments_ProjectLawId"
                ON "ParliamentInitiativeDocuments" ("ProjectLawId");
            CREATE INDEX "IX_ParliamentInitiativeEvents_ProjectLawId_PhaseCode_PhaseDate"
                ON "ParliamentInitiativeEvents" ("ProjectLawId", "PhaseCode", "PhaseDate");
            CREATE INDEX "IX_ParliamentInitiativeInterventions_ParliamentInitiativeEventId"
                ON "ParliamentInitiativeInterventions" ("ParliamentInitiativeEventId");
            CREATE INDEX "IX_ParliamentInitiativeInterventions_ProjectLawId"
                ON "ParliamentInitiativeInterventions" ("ProjectLawId");
            CREATE INDEX "IX_ParliamentInitiativePublications_ParliamentInitiativeEventId"
                ON "ParliamentInitiativePublications" ("ParliamentInitiativeEventId");
            CREATE INDEX "IX_ParliamentInitiativePublications_ProjectLawId"
                ON "ParliamentInitiativePublications" ("ProjectLawId");
            CREATE INDEX "IX_ParliamentInitiativeVoteBlocks_ParliamentInitiativeVoteId"
                ON "ParliamentInitiativeVoteBlocks" ("ParliamentInitiativeVoteId");
            CREATE INDEX "IX_ParliamentInitiativeVotes_ParliamentInitiativeEventId"
                ON "ParliamentInitiativeVotes" ("ParliamentInitiativeEventId");
            CREATE INDEX "IX_ParliamentInitiativeVotes_ProjectLawId_Stage_VoteDate"
                ON "ParliamentInitiativeVotes" ("ProjectLawId", "Stage", "VoteDate");
            CREATE INDEX "IX_ProjectLaws_LastImportRunId"
                ON "ProjectLaws" ("LastImportRunId");
            CREATE INDEX "IX_ProjectLaws_SourceId"
                ON "ProjectLaws" ("SourceId");
            CREATE INDEX "IX_ProjectLaws_SourceIdText"
                ON "ProjectLaws" ("SourceIdText");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ParliamentImportErrors";
            DROP TABLE IF EXISTS "ParliamentImportSkips";
            DROP TABLE IF EXISTS "ParliamentInitiativeAuthors";
            DROP TABLE IF EXISTS "ParliamentInitiativeDocuments";
            DROP TABLE IF EXISTS "ParliamentInitiativeInterventions";
            DROP TABLE IF EXISTS "ParliamentInitiativePublications";
            DROP TABLE IF EXISTS "ParliamentInitiativeVoteBlocks";
            DROP TABLE IF EXISTS "ParliamentInitiativeVotes";
            DROP TABLE IF EXISTS "ParliamentInitiativeEvents";

            ALTER TABLE "ProjectLaws"
                DROP CONSTRAINT IF EXISTS "FK_ProjectLaws_ParliamentImportRuns_LastImportRunId";

            DROP TABLE IF EXISTS "ParliamentImportRuns";

            DROP INDEX IF EXISTS "IX_ProjectLaws_LastImportRunId";
            DROP INDEX IF EXISTS "IX_ProjectLaws_SourceId";
            DROP INDEX IF EXISTS "IX_ProjectLaws_SourceIdText";

            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "SourceIdText";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "SourceHash";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "ImportedAtUtc";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "LastImportRunId";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeNumber";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeTypeCode";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeTypeDescription";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeSelection";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeObservations";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeTextSubstitution";
            ALTER TABLE "ProjectLaws" DROP COLUMN IF EXISTS "InitiativeTextSubstitutionField";
            """);
    }
}
