using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260701000500_AddParliamentaryGroups")]
public class AddParliamentaryGroups : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "ParliamentaryGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Legislature" text NOT NULL,
                "Acronym" text NOT NULL,
                "Name" text NULL,
                CONSTRAINT "PK_ParliamentaryGroups" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ParliamentaryGroups_Legislature_Acronym"
                ON "ParliamentaryGroups" ("Legislature", "Acronym");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ParliamentaryGroups";
            """);
    }
}
