using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260701000300_AddRedactionPipelineTables")]
public class AddRedactionPipelineTables : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "ParliamentDeputies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Legislature" text NOT NULL,
                "SourceCadId" text NULL,
                "SourceDeputyId" text NULL,
                "FullName" text NULL,
                "ParliamentaryName" text NULL,
                "Constituency" text NULL,
                "PartyAcronym" text NULL,
                "Situation" text NULL,
                CONSTRAINT "PK_ParliamentDeputies" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "ParliamentRedactionTerms" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Legislature" text NOT NULL,
                "Term" text NOT NULL,
                "TermKind" text NOT NULL,
                CONSTRAINT "PK_ParliamentRedactionTerms" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "ParliamentDocumentContents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentInitiativeDocumentId" integer NOT NULL,
                "SourceUrl" text NULL,
                "SourceContentHash" text NULL,
                "SourceContentLength" bigint NULL,
                "ExtractedContentHash" text NULL,
                "RedactedContentHash" text NULL,
                "RedactedContentText" text NULL,
                "RedactedContentHtml" text NULL,
                "ExtractionStatus" text NOT NULL,
                "RedactionStatus" text NOT NULL,
                "ExtractorKind" text NULL,
                "RedactionPolicyVersion" text NULL,
                "ErrorMessage" text NULL,
                "ExtractedAtUtc" timestamp with time zone NULL,
                "RedactedAtUtc" timestamp with time zone NULL,
                CONSTRAINT "PK_ParliamentDocumentContents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ParliamentDocumentContents_ParliamentInitiativeDocuments_ParliamentInitiativeDocumentId"
                    FOREIGN KEY ("ParliamentInitiativeDocumentId")
                    REFERENCES "ParliamentInitiativeDocuments" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ParliamentDocumentContents_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_ParliamentDeputies_Legislature_SourceDeputyId"
                ON "ParliamentDeputies" ("Legislature", "SourceDeputyId");
            CREATE INDEX IF NOT EXISTS "IX_ParliamentDeputies_Legislature_SourceCadId"
                ON "ParliamentDeputies" ("Legislature", "SourceCadId");
            CREATE INDEX IF NOT EXISTS "IX_ParliamentRedactionTerms_Legislature_Term"
                ON "ParliamentRedactionTerms" ("Legislature", "Term");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ParliamentDocumentContents_ParliamentInitiativeDocumentId"
                ON "ParliamentDocumentContents" ("ParliamentInitiativeDocumentId");
            CREATE INDEX IF NOT EXISTS "IX_ParliamentDocumentContents_ProjectLawId"
                ON "ParliamentDocumentContents" ("ProjectLawId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ParliamentDocumentContents";
            DROP TABLE IF EXISTS "ParliamentRedactionTerms";
            DROP TABLE IF EXISTS "ParliamentDeputies";
            """);
    }
}
