using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260923000100_AddProposalTopicTaxonomy")]
public class AddProposalTopicTaxonomy : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "ProposalTopicTaxonomyVersions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Version" text NOT NULL,
                "GeneratedAtUtc" timestamp with time zone NULL,
                "EmbeddingProvider" text NOT NULL,
                "EmbeddingModel" text NOT NULL,
                "EmbeddingDimensions" integer NULL,
                "AutoSimilarityThreshold" double precision NULL,
                "ReviewSimilarityThreshold" double precision NULL,
                "MinSimilarityMargin" double precision NULL,
                "LowSupportMinExamples" integer NULL,
                "LowSupportAutoThreshold" double precision NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ProposalTopicTaxonomyVersions" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProposalTopicTaxonomyVersions_Version"
                ON "ProposalTopicTaxonomyVersions" ("Version");

            CREATE TABLE IF NOT EXISTS "ProposalTopicParents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TaxonomyVersionId" integer NOT NULL,
                "Slug" text NOT NULL,
                "Label" text NOT NULL,
                "Description" text NULL,
                "DisplayOrder" integer NOT NULL,
                "SourceClusterIdsJson" text NULL,
                CONSTRAINT "PK_ProposalTopicParents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProposalTopicParents_ProposalTopicTaxonomyVersions_TaxonomyVersionId"
                    FOREIGN KEY ("TaxonomyVersionId")
                    REFERENCES "ProposalTopicTaxonomyVersions" ("Id")
                    ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProposalTopicParents_TaxonomyVersionId_Slug"
                ON "ProposalTopicParents" ("TaxonomyVersionId", "Slug");

            CREATE TABLE IF NOT EXISTS "ProposalSubtopics" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TaxonomyVersionId" integer NOT NULL,
                "ParentTopicId" integer NOT NULL,
                "Slug" text NOT NULL,
                "Label" text NOT NULL,
                "Description" text NULL,
                "DisplayOrder" integer NOT NULL,
                "SourceClusterIdsJson" text NULL,
                "CentroidIndex" integer NULL,
                "SupportCount" integer NULL,
                "SupportQuality" text NULL,
                "SimilarityMin" double precision NULL,
                "SimilarityP05" double precision NULL,
                "SimilarityP10" double precision NULL,
                "SimilarityP25" double precision NULL,
                "SimilarityMedian" double precision NULL,
                "SimilarityMean" double precision NULL,
                "RecommendedAutoThreshold" double precision NULL,
                CONSTRAINT "PK_ProposalSubtopics" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProposalSubtopics_ProposalTopicParents_ParentTopicId"
                    FOREIGN KEY ("ParentTopicId")
                    REFERENCES "ProposalTopicParents" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ProposalSubtopics_ProposalTopicTaxonomyVersions_TaxonomyVersionId"
                    FOREIGN KEY ("TaxonomyVersionId")
                    REFERENCES "ProposalTopicTaxonomyVersions" ("Id")
                    ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_ProposalSubtopics_ParentTopicId"
                ON "ProposalSubtopics" ("ParentTopicId");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProposalSubtopics_TaxonomyVersionId_Slug"
                ON "ProposalSubtopics" ("TaxonomyVersionId", "Slug");

            CREATE TABLE IF NOT EXISTS "ProjectLawTopicAssignments" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProjectLawId" integer NOT NULL,
                "ParliamentDocumentContentId" integer NULL,
                "TaxonomyVersionId" integer NOT NULL,
                "SubtopicId" integer NULL,
                "BestSubtopicId" integer NULL,
                "SecondBestSubtopicId" integer NULL,
                "AssignmentMethod" text NOT NULL,
                "AssignmentStatus" text NOT NULL,
                "AssignmentConfidence" double precision NULL,
                "BestSimilarity" double precision NULL,
                "SecondBestSimilarity" double precision NULL,
                "SimilarityMargin" double precision NULL,
                "EmbeddingProvider" text NOT NULL,
                "EmbeddingModel" text NOT NULL,
                "SourceDocumentHash" text NULL,
                "IsCurrent" boolean NOT NULL DEFAULT TRUE,
                "AssignedAtUtc" timestamp with time zone NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "UpdatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ProjectLawTopicAssignments" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProjectLawTopicAssignments_ParliamentDocumentContents_ParliamentDocumentContentId"
                    FOREIGN KEY ("ParliamentDocumentContentId")
                    REFERENCES "ParliamentDocumentContents" ("Id")
                    ON DELETE SET NULL,
                CONSTRAINT "FK_ProjectLawTopicAssignments_ProjectLaws_ProjectLawId"
                    FOREIGN KEY ("ProjectLawId")
                    REFERENCES "ProjectLaws" ("Id")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ProjectLawTopicAssignments_ProposalSubtopics_BestSubtopicId"
                    FOREIGN KEY ("BestSubtopicId")
                    REFERENCES "ProposalSubtopics" ("Id")
                    ON DELETE SET NULL,
                CONSTRAINT "FK_ProjectLawTopicAssignments_ProposalSubtopics_SecondBestSubtopicId"
                    FOREIGN KEY ("SecondBestSubtopicId")
                    REFERENCES "ProposalSubtopics" ("Id")
                    ON DELETE SET NULL,
                CONSTRAINT "FK_ProjectLawTopicAssignments_ProposalSubtopics_SubtopicId"
                    FOREIGN KEY ("SubtopicId")
                    REFERENCES "ProposalSubtopics" ("Id")
                    ON DELETE SET NULL,
                CONSTRAINT "FK_ProjectLawTopicAssignments_ProposalTopicTaxonomyVersions_TaxonomyVersionId"
                    FOREIGN KEY ("TaxonomyVersionId")
                    REFERENCES "ProposalTopicTaxonomyVersions" ("Id")
                    ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_ParliamentDocumentContentId"
                ON "ProjectLawTopicAssignments" ("ParliamentDocumentContentId");

            CREATE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_BestSubtopicId"
                ON "ProjectLawTopicAssignments" ("BestSubtopicId");

            CREATE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_SecondBestSubtopicId"
                ON "ProjectLawTopicAssignments" ("SecondBestSubtopicId");

            CREATE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_SubtopicId"
                ON "ProjectLawTopicAssignments" ("SubtopicId");

            CREATE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_TaxonomyVersionId_AssignmentStatus"
                ON "ProjectLawTopicAssignments" ("TaxonomyVersionId", "AssignmentStatus");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProjectLawTopicAssignments_ProjectLawId_TaxonomyVersionId_Current"
                ON "ProjectLawTopicAssignments" ("ProjectLawId", "TaxonomyVersionId")
                WHERE "IsCurrent" = TRUE;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "ProjectLawTopicAssignments";
            DROP TABLE IF EXISTS "ProposalSubtopics";
            DROP TABLE IF EXISTS "ProposalTopicParents";
            DROP TABLE IF EXISTS "ProposalTopicTaxonomyVersions";
            """);
    }
}
