using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Parlamento.Infrastructure.Persistence;

namespace Parlamento.Infrastructure.Migrations;

[DbContext(typeof(DatabaseContext))]
[Migration("20260626000100_InitialPostgresSchema")]
public class InitialPostgresSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE "PoliticalParties" (
                "partyAcronym" text NOT NULL,
                "fullName" text NOT NULL,
                "logoLink" text NOT NULL,
                CONSTRAINT "PK_PoliticalParties" PRIMARY KEY ("partyAcronym")
            );

            CREATE TABLE "Users" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserName" text NOT NULL,
                "Email" text NOT NULL,
                "Password" text NOT NULL,
                "ProfilePic" integer NOT NULL,
                "googleIDToken" text NULL,
                "facebookIDToken" text NULL,
                CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
            );

            CREATE TABLE "VotingResult" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "isUninamous" boolean NOT NULL,
                CONSTRAINT "PK_VotingResult" PRIMARY KEY ("Id")
            );

            CREATE TABLE "PartyStats" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "PoliticalPartypartyAcronym" text NOT NULL,
                "PartyAffectionScore" double precision NOT NULL,
                "UserId" integer NULL,
                "totalAffectionPoints" double precision NOT NULL,
                "totalAmountOfProposalsVotedOn" integer NOT NULL,
                CONSTRAINT "PK_PartyStats" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_PartyStats_PoliticalParties_PoliticalPartypartyAcronym"
                    FOREIGN KEY ("PoliticalPartypartyAcronym")
                    REFERENCES "PoliticalParties" ("partyAcronym")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_PartyStats_Users_UserId"
                    FOREIGN KEY ("UserId")
                    REFERENCES "Users" ("Id")
            );

            CREATE TABLE "ProjectLaws" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "SourceId" integer NOT NULL,
                "Legislatura" text NOT NULL,
                "Score" integer NOT NULL,
                "amountOfUsersInterested" integer NOT NULL,
                "totalAmountOfVotesFromUsers" integer NOT NULL,
                "VoteDate" text NOT NULL,
                "ProposingPartypartyAcronym" text NOT NULL,
                "ProposalTitle" text NOT NULL,
                "FullProposalTextLink" text NOT NULL,
                "ProposalTextHTML" text NULL,
                "ProposalResult" integer NULL,
                "VotingResultGeneralityId" integer NULL,
                "VotingResultSpecialityId" integer NULL,
                CONSTRAINT "PK_ProjectLaws" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProjectLaws_PoliticalParties_ProposingPartypartyAcronym"
                    FOREIGN KEY ("ProposingPartypartyAcronym")
                    REFERENCES "PoliticalParties" ("partyAcronym")
                    ON DELETE CASCADE,
                CONSTRAINT "FK_ProjectLaws_VotingResult_VotingResultGeneralityId"
                    FOREIGN KEY ("VotingResultGeneralityId")
                    REFERENCES "VotingResult" ("Id"),
                CONSTRAINT "FK_ProjectLaws_VotingResult_VotingResultSpecialityId"
                    FOREIGN KEY ("VotingResultSpecialityId")
                    REFERENCES "VotingResult" ("Id")
            );

            CREATE TABLE "Vote" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "VoteDate" timestamp with time zone NOT NULL,
                "ProjectLawID" integer NOT NULL,
                "VotingOrientation" integer NOT NULL,
                "UserId" integer NULL,
                CONSTRAINT "PK_Vote" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Vote_Users_UserId"
                    FOREIGN KEY ("UserId")
                    REFERENCES "Users" ("Id")
            );

            CREATE TABLE "VotingBlock" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "isUninamousWithinParty" boolean NULL,
                "numberOfDeputies" integer NULL,
                "politicalPartyAcronym" text NOT NULL,
                "votingOrientation" integer NOT NULL,
                "VotingResultId" integer NULL,
                CONSTRAINT "PK_VotingBlock" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_VotingBlock_VotingResult_VotingResultId"
                    FOREIGN KEY ("VotingResultId")
                    REFERENCES "VotingResult" ("Id")
            );

            CREATE INDEX "IX_PartyStats_PoliticalPartypartyAcronym"
                ON "PartyStats" ("PoliticalPartypartyAcronym");

            CREATE INDEX "IX_PartyStats_UserId"
                ON "PartyStats" ("UserId");

            CREATE INDEX "IX_ProjectLaws_ProposingPartypartyAcronym"
                ON "ProjectLaws" ("ProposingPartypartyAcronym");

            CREATE INDEX "IX_ProjectLaws_VotingResultGeneralityId"
                ON "ProjectLaws" ("VotingResultGeneralityId");

            CREATE INDEX "IX_ProjectLaws_VotingResultSpecialityId"
                ON "ProjectLaws" ("VotingResultSpecialityId");

            CREATE INDEX "IX_Vote_UserId"
                ON "Vote" ("UserId");

            CREATE INDEX "IX_VotingBlock_VotingResultId"
                ON "VotingBlock" ("VotingResultId");
            """);

        migrationBuilder.Sql("""
            INSERT INTO "PoliticalParties" ("partyAcronym", "fullName", "logoLink") VALUES
            ('PSD', 'Partido Social-Democrata', 'https://pt.wikipedia.org/wiki/Ficheiro:Logo_PSD_cor.PNG'),
            ('PS', 'Partido Socialista', 'https://pt.wikipedia.org/wiki/Ficheiro:Partido_Socialista_%28Portugal%29.png'),
            ('BE', 'Bloco de Esquerda', 'https://pt.wikipedia.org/wiki/Bloco_de_Esquerda'),
            ('PCP', 'Partido Comunista Português', 'https://pt.m.wikipedia.org/wiki/Ficheiro:Portuguese_Communist_Party_logo.svg'),
            ('CDSPP', 'Coligação Democrática Unitária', 'https://pt.m.wikipedia.org/wiki/Ficheiro:CDS_%E2%80%93_People%27s_Party_logo.svg'),
            ('PAN', 'Pessoas-Animais-Natureza', 'https://pt.wikipedia.org/wiki/Pessoas%E2%80%93Animais%E2%80%93Natureza'),
            ('L', 'Partido Livre', 'https://pt.m.wikipedia.org/wiki/Ficheiro:Partido_LIVRE_logo.png'),
            ('IL', 'Iniciativa Liberal', 'https://pt.m.wikipedia.org/wiki/Ficheiro:Iniciativa_Liberal_logo_1.png'),
            ('CH', 'Chega', 'https://en.wikipedia.org/wiki/File:Logo_of_the_Chega_(political_party).svg'),
            ('Governo', 'Governo', 'https://pt.wikipedia.org/wiki/Ficheiro:Trollface.png');
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "PartyStats";
            DROP TABLE IF EXISTS "Vote";
            DROP TABLE IF EXISTS "VotingBlock";
            DROP TABLE IF EXISTS "ProjectLaws";
            DROP TABLE IF EXISTS "Users";
            DROP TABLE IF EXISTS "PoliticalParties";
            DROP TABLE IF EXISTS "VotingResult";
            """);
    }
}

