name: Test and lint frontend

on: pull_request

jobs:
  lint_frontend:
    name: "Lint frontend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.3.2"

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ github.ref }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-${{ github.ref }}-

      - run: flutter pub get
      - run: flutter analyze --no-pub --preamble .

  test_frontend:
    name: "Test frontend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.3.2"

      - run: flutter pub get
      - run: flutter test
